### ISSUE TITLE
リモートブランチ名と違う名前のブランチをプッシュしてしまった

### ISSUE THREAD

**Issue by YamashitaRintaro** [YamashitaRintaro/prep_method_training#61]
### 質問内容・実現したいこと
リモートブランチの名前とプッシュしたブランチの名前が違い、エラーが発生したので解消したい。

### 現状発生している問題・エラーメッセージ
1. 41_fix_last_voiceブランチでコミット
2. 42_adjustにブランチ名を変更
3. 42_adjustでコミット
4. git push
5. 以下のエラー
```
yamashitarintarou@yamashitarintarounoMacBook-Pro prep_method_training % git status
On branch 42_adjust
Your branch is ahead of 'origin/41_fix_last_voice' by 2 commits.
  (use "git push" to publish your local commits)

nothing to commit, working tree clean
yamashitarintarou@yamashitarintarounoMacBook-Pro prep_method_training % git push
fatal: The upstream branch of your current branch does not match
the name of your current branch.  To push to the upstream branch
on the remote, use

    git push origin HEAD:41_fix_last_voice

To push to the branch of the same name on the remote, use

    git push origin HEAD

To choose either option permanently, see push.default in 'git help config'.
```

### エラーから考えられる原因

リモートブランチの名前とプッシュしたブランチの名前が違う。
今回の場合、リモートブランチ名は`41_fix_last_voice` だが、プッシュしたブランチ名は`42_adjust`

### 試したこと
```
#リモートブランチ(origin/41_fix_last_voice)に対して、ローカルブランチ(42_adjust)はpushしていない
git status
On branch 42_adjust
Your branch is ahead of 'origin/41_fix_last_voice' by 2 commits.
  (use "git push" to publish your local commits)

nothing to commit, working tree clean
```
```
git branch -r
origin/41_fix_last_voice
```
```
git branch -vv
* 42_adjust   e57d616 [origin/41_fix_last_voice: ahead 2]
```
## 質問内容
3択で迷ったので、どれを実行するべきか。
僕は選択肢１を実行するつもりでしたが、確証が持てなかったので質問させていただきました。
全て適切でない場合、解決策を教えていただきたいです。

### 選択肢1
エラーメッセージに従う
現在のブランチ名をリモートブランチ名に変更してpushするイメージだが、確証が持てない。

```
git push origin HEAD:41_fix_last_voice
```

参考：https://stackoverflow.com/questions/24864700/fatal-the-upstream-branch-of-your-current-branch-does-not-match-the-name-of-you/24865780#24865780

### 選択肢2
リモートのブランチ名を一旦削除してからもう一度プッシュ

```
#①リモートブランチを削除
git push origin 41_fix_last_voice

#②次にプッシュする際にブランチの紐付けをする
git push --set-upstream origin 42_adjust
```

参考：https://qiita.com/kmnohno3/items/587c619d95a86e7dbaef

### 選択肢3

ブランチの上流ブランチを取り消す
```
git branch --unset-upstream
```

参考：https://stackoverflow.com/questions/24864700/fatal-the-upstream-branch-of-your-current-branch-does-not-match-the-name-of-you

### 参考にしたURL
https://stackoverflow.com/questions/24864700/fatal-the-upstream-branch-of-your-current-branch-does-not-match-the-name-of-you
https://qiita.com/kmnohno3/items/587c619d95a86e7dbaef
https://qiita.com/suwa3/items/2b325a10cb1a8b96c951
https://teratail.com/questions/141536
https://codeclub965.com/?p=2550
https://www-creators.com/archives/1065

**Comment by busitora** [comment]
そのリモートブランチは削除していいものかどうかによっても変わりそうですね。

個人的に remote ブランチと local ブランチで push でエラーになったら、
remoteがどうなってもいいなら 2ですが、1でもいいと思います！

**Comment by YamashitaRintaro** [comment]
ご回答ありがとうございます！
```
git push origin HEAD:41_fix_last_voice
```
を実行した結果、以下のようになりました。
```
git status                            
On branch 42_adjust
Your branch is up to date with 'origin/41_fix_last_voice'.

nothing to commit, working tree clean
```
ブランチ名は`42_adjust`のままなので、
```
git branch -m 41_fix_last_voice
```
でリモートブランチ名と合わせる必要があるのではと考えたのですが、正しいでしょうか？

**Comment by busitora** [comment]
force push や reset hard 等しない限り localと remote で整合性とれなくなることはないので、色々試してみてください！

**Comment by YamashitaRintaro** [comment]
ご回答ありがとうございます！
承知しました！失敗しても誰にも迷惑をかけないので、色々試してみます！
